language: python
sudo: False
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO="Django>=1.8.0,<1.9.0"
  - DJANGO="Django>=1.10,<1.11.0"
  - DJANGO="Django>=1.11,<1.12.0"
install:
  - pip install $DJANGO
  - pip install .
  - pip install flake8
  - pip install coveralls
script:
  - flake8 s3sign
  - python runtests.py
  - coverage run --source=s3sign runtests.py
after_success:
  - coveralls
