language: python
sudo: False
python:
  - "2.7"
  - "3.5"
install:
  - pip install .
  - pip install flake8
  - pip install coveralls
script:
  - flake8 s3sign
  - python runtests.py
  - coverage run --source=s3sign runtests.py
after_success:
  - coveralls
